#!/usr/bin/env node
/**
 * Multi-Strategy Transcript Extractor CLI
 *
 * Extracts transcripts from YouTube videos using multiple fallback strategies.
 * Outputs JSON to stdout, logs to stderr.
 *
 * Usage:
 *   node cli.js <video-url-or-id>
 *
 * Output (JSON):
 *   On success: { transcript, segment_count, source, language?, metadata? }
 *   On failure: { error, error_type }
 */

import { TranscriptService } from "./service/transcript-service.js";
import { logger } from "./utils/logger.js";

interface CLIOutput {
  transcript?: string;
  segment_count?: number;
  source?: string;
  language?: string;
  is_auto_generated?: boolean;
  metadata?: Record<string, unknown>;
  error?: string;
  error_type?: string;
}

async function main(): Promise<void> {
  const videoInput = process.argv[2];

  if (!videoInput) {
    const output: CLIOutput = {
      error: "Missing video URL or ID argument",
      error_type: "invalid_input",
    };
    console.log(JSON.stringify(output));
    process.exit(2);
  }

  try {
    const service = new TranscriptService();
    const result = await service.extractTranscript(videoInput);

    if (result.success) {
      // Count segments (lines starting with timestamp)
      const segmentCount = result.transcript
        .split("\n")
        .filter((line) => line.startsWith("[")).length;

      const output: CLIOutput = {
        transcript: result.transcript,
        segment_count: result.segmentCount ?? segmentCount,
        source: result.source,
        language: result.language,
        is_auto_generated: result.isAutoGenerated,
        metadata: result.metadata as Record<string, unknown>,
      };

      console.log(JSON.stringify(output));
      process.exit(0);
    } else {
      const output: CLIOutput = {
        error: result.error,
        error_type: result.errorType,
      };

      console.log(JSON.stringify(output));
      process.exit(1);
    }
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : String(error);
    logger.error({ error: errorMessage }, "Unhandled error in CLI");

    const output: CLIOutput = {
      error: errorMessage,
      error_type: "unknown",
    };

    console.log(JSON.stringify(output));
    process.exit(1);
  }
}

main();
