/**
 * Apify YouTube Scraper API Types
 *
 * Type definitions for the Apify YouTube Scraper API responses and requests.
 * Extracted for reusability and maintainability.
 *
 * @see https://apify.com/streamers/youtube-scraper
 */

/**
 * Subtitle track from Apify response
 */
export interface ApifySubtitle {
  /** URL to download the SRT file (may be null if embedded) */
  srtUrl: string | null;
  /** Type of subtitle track */
  type: "auto_generated" | "standard";
  /** Language code (e.g., "en", "de") */
  language: string;
  /** Inline SRT content */
  srt: string;
}

/**
 * Video result from Apify YouTube Scraper
 * Contains full video metadata and subtitles
 */
export interface ApifyVideoResult {
  // Core identifiers
  id: string;
  url: string;
  type: string;

  // Titles and descriptions
  title: string;
  translatedTitle: string | null;
  text: string; // Video description
  translatedText: string | null;

  // Media
  thumbnailUrl: string;
  duration: string;

  // Engagement metrics
  viewCount: number;
  likes: number;
  commentsCount: number;
  commentsTurnedOff: boolean;

  // Channel information
  channelName: string;
  channelUrl: string;
  channelUsername: string;
  channelId: string;
  numberOfSubscribers: number;
  location: string | null;

  // Publishing info
  date: string;

  // Content flags
  isMonetized: boolean | null;
  isMembersOnly: boolean;
  isPaidContent: boolean;
  hashtags: string[];

  // Subtitles (optional)
  subtitles?: ApifySubtitle[];
}

/**
 * Request body for Apify YouTube Scraper API
 */
export interface ApifyScraperRequest {
  downloadSubtitles: boolean;
  startUrls: Array<{ url: string }>;
  subtitlesFormat: "srt" | "vtt" | "xml" | "plaintext";
  subtitlesLanguage: string;
  preferAutoGeneratedSubtitles: boolean;
  maxResults: number;
  maxResultsShorts: number;
  maxResultStreams: number;
}

/**
 * Supported language codes for Apify subtitle download
 */
export const APIFY_SUPPORTED_LANGUAGES = [
  "any",
  "en",
  "de",
  "es",
  "fr",
  "it",
  "ja",
  "ko",
  "nl",
  "pt",
  "ru",
] as const;

export type ApifySupportedLanguage = (typeof APIFY_SUPPORTED_LANGUAGES)[number];
