/**
 * Watch Page Types
 *
 * Type definitions for the watch page transcript fetcher.
 */

export interface TranscriptLine {
  text: string;
  start: number;
  dur: number;
}

export interface CaptionTrack {
  languageCode: string;
  name: string;
  isAutoGenerated: boolean;
}

export interface AdChapter {
  title: string;
  startMs: number;
  endMs: number;
}

export interface WatchPageVideoMetadata {
  title: string;
  author: string;
  subscriberCount: string;
  viewCount: string;
  publishDate: string;
}

export interface PageData {
  visitorData: string;
  clientVersion: string;
  availableLanguages: CaptionTrack[];
  adChapters: AdChapter[];
  metadata: WatchPageVideoMetadata;
}

export interface WatchPageSubtitleResult {
  lines: TranscriptLine[];
  requestedLang: string;
  actualLang: string;
  availableLanguages: CaptionTrack[];
  adChapters: AdChapter[];
  metadata: WatchPageVideoMetadata;
}

export interface TranscriptSnippetRun {
  text?: string;
}

export interface TranscriptSnippet {
  runs?: TranscriptSnippetRun[];
  elementsAttributedString?: {
    content?: string;
  };
}

export interface TranscriptSegmentRenderer {
  snippet?: TranscriptSnippet;
  startMs?: string;
  endMs?: string;
}

export interface TranscriptSegmentItem {
  transcriptSegmentRenderer?: TranscriptSegmentRenderer;
}

export interface TranscriptApiResponse {
  error?: {
    message?: string;
    code?: string;
  };
  actions?: Array<{
    updateEngagementPanelAction?: {
      content?: {
        transcriptRenderer?: {
          content?: {
            transcriptSearchPanelRenderer?: {
              body?: {
                transcriptSegmentListRenderer?: {
                  initialSegments?: TranscriptSegmentItem[];
                };
              };
            };
          };
        };
      };
    };
    elementsCommand?: {
      transformEntityCommand?: {
        arguments?: {
          transformTranscriptSegmentListArguments?: {
            overwrite?: {
              initialSegments?: TranscriptSegmentItem[];
            };
          };
        };
      };
    };
  }>;
}
