/**
 * Transcript Service Types
 *
 * Shared types for the multi-strategy transcript extraction system.
 * Following SOLID principles - all types in one place for maintainability.
 */

/**
 * Video metadata extracted along with transcript
 */
export interface VideoMetadata {
  title?: string;
  description?: string;
  thumbnailUrl?: string;
  viewCount?: number;
  publishedAt?: string;
  likes?: number;
  channelName?: string;
  channelUrl?: string;
  channelId?: string;
  subscriberCount?: number;
  duration?: string;
  commentsCount?: number;
}

/**
 * Successful transcript extraction result
 */
export interface TranscriptResult {
  success: true;
  transcript: string;
  source: TranscriptSource;
  segmentCount?: number;
  language?: string;
  isAutoGenerated?: boolean;
  metadata?: VideoMetadata;
}

/**
 * Failed transcript extraction result
 */
export interface TranscriptError {
  success: false;
  error: string;
  errorType: TranscriptErrorType;
  source?: TranscriptSource;
}

/**
 * Union type for transcript extraction outcomes
 */
export type TranscriptOutcome = TranscriptResult | TranscriptError;

/**
 * Type guard: Check if outcome is a successful result
 */
export function isTranscriptResult(
  outcome: TranscriptOutcome
): outcome is TranscriptResult {
  return outcome.success === true;
}

/**
 * Type guard: Check if outcome is an error
 */
export function isTranscriptError(
  outcome: TranscriptOutcome
): outcome is TranscriptError {
  return outcome.success === false;
}

/**
 * Sources for transcript extraction (strategies)
 */
export type TranscriptSource =
  | "youtubei"
  | "watch-page"
  | "ytdlp"
  | "youtube-api"
  | "apify"
  | "cache";

/**
 * Error types for precise error handling and fallback decisions
 */
export enum TranscriptErrorType {
  NO_CAPTIONS = "no_captions",
  VIDEO_UNAVAILABLE = "video_unavailable",
  VIDEO_PRIVATE = "video_private",
  VIDEO_LIVE = "video_live",
  AGE_RESTRICTED = "age_restricted",
  RATE_LIMITED = "rate_limited",
  TIMEOUT = "timeout",
  NETWORK_ERROR = "network_error",
  PARSE_ERROR = "parse_error",
  UNKNOWN = "unknown",
}

/**
 * Transcript segment with timing information
 */
export interface TranscriptSegment {
  startMs: number;
  endMs?: number;
  text: string;
}

/**
 * Options for transcript extraction
 */
export interface TranscriptOptions {
  /** Preferred languages in order (e.g., ["en", "*"]) */
  preferredLanguages?: string[];
  /** Include [HH:MM:SS] timestamps in output */
  includeTimestamps?: boolean;
  /** Timeout in milliseconds */
  timeoutMs?: number;
  /** Skip cache lookup */
  skipCache?: boolean;
  /** Working directory for temp files */
  workDir?: string;
}

/**
 * Strategy configuration
 */
export interface StrategyConfig {
  /** Strategy name for logging */
  name: string;
  /** Timeout in milliseconds */
  timeoutMs: number;
  /** Whether this strategy is enabled */
  enabled: boolean;
  /** Priority (lower = higher priority) */
  priority: number;
}

/**
 * Default extraction options
 */
export const DEFAULT_TRANSCRIPT_OPTIONS: Required<TranscriptOptions> = {
  preferredLanguages: ["en", "*"],
  includeTimestamps: true,
  timeoutMs: 60000,
  skipCache: false,
  workDir: "/tmp/transcript-extraction",
};

/**
 * Strategy-specific timeouts
 */
export const STRATEGY_TIMEOUTS = {
  watchPage: 60000, // 60 seconds (direct HTTPS)
  youtubei: 60000, // 60 seconds
  ytdlp: 180000, // 180 seconds (slower with cookies)
  youtubeApi: 15000, // 15 seconds (fast API)
  apify: 180000, // 180 seconds (external API)
} as const;

/**
 * Memory assessment result for strategy availability
 */
export interface StrategyMemoryAssessment {
  enabled: boolean;
  reason: string;
  availableMb?: number;
  requiredMb?: number;
}
